### ISSUE TITLE
Webロゴ掲載（株式会社はてな さま）

### ISSUE THREAD

**Issue by shomatan** [scalamatsuri/2024.scalamatsuri.org#125]
## やること

- [x] リポジトリにロゴを入れる
  - ロゴ画像: hatena.png
- [x] `data/sponsors.json` を変更する
- [x] master branch に向けて PullRequest を送る
- [x] staging 環境で表示を確認する
- [x] master から production に向けて自動で PullRequest が作成されるのでマージ
- [x] merge 後、production 環境の Web サイトに反映されていることを確認する

### 大名

```
  {
    "id": "DAIMYO_1",
    "type": "DAIMYO",
    "ja": {
      "name": "大名スポンサー1"
    },
    "en": {
      "name": "Daimyo Sponsor1"
    },
    "logo": "/img/sponsors/scalamatsuri_logo.png",
    "url": "",
    "textHtml": "<p>大名スポンサー1です。</p>",
    "slideHtml": ""
  },
```

**Comment by tomoco95** [comment]
掲載しました！
