### ISSUE TITLE
Webロゴ掲載（株式会社ギークニアさま）

### ISSUE THREAD

**Issue by shomatan** [scalamatsuri/2024.scalamatsuri.org#151]
## やること

- [x] リポジトリにロゴを入れる
  - ロゴ画像:
- [x] `data/sponsors.json` を変更する
- [x] master branch に向けて PullRequest を送る
- [x] staging 環境で表示を確認する
- [x] master から production に向けて自動で PullRequest が作成されるのでマージ
- [x] merge 後、production 環境の Web サイトに反映されていることを確認する
- [x] speakerdeck のスライドが指定された場合、URL のみ切り取って `"speakerdeckUrl": ""` に指定する。
  - 2024 年 2 月: 現在 slideHtml が機能しておらず、iframe 内部が空で表示されてしまう模様。
  - 2024 年 2 月: speakerdeck 以外の URL を指定された場合は別途 WEB サイトチームにご相談ください。

### 侍

```
  {
    "id": "SAMURAI_1",
    "type": "SAMURAI",
    "ja": {
      "name": "侍スポンサー1"
    },
    "en": {
      "name": "Samurai Sponsor1"
    },
    "logo": "/img/sponsors/scalamatsuri_logo.png",
    "url": "",
    "textHtml": "<p>侍スポンサー1です。</p>",
    "slideHtml": "",
    "speakerdeckUrl": ""
  },
```

ロゴ画像：https://drive.google.com/open?id=1CcFZlque-wGSx_cCp2qLcu5vuJeindn1

**Comment by shomatan** [comment]
~~ロゴ提出待ち~~

**Comment by shomatan** [comment]
ロゴ: https://drive.google.com/file/d/1c1u14nMyv4krGfj0NszoTziy0pZ6N7em/view

**Comment by tomoco95** [comment]
こちら完了しています。対応ありがとうございました！
