### ISSUE TITLE
Webロゴ掲載(株式会社ギークニア様)

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2024.scalamatsuri.org#160]
- [ ] リポジトリにロゴを入れる
- [ ] `data/sponsors.json` を変更する
- [ ] master branchに向けてPullRequestを送る
- [ ] staging環境で表示を確認する
- [ ] masterからproductionに向けて自動でPullRequestが作成されるのでマージ
- [ ] merge後、production環境のWebサイトに反映されていることを確認する

template: 
```
,{
 "name": "株式会社ギークニア",
 "logo": "",
 "url": "https://geekneer.com/"
}
```
ロゴ画像：https://drive.google.com/open?id=1c1u14nMyv4krGfj0NszoTziy0pZ6N7em

**Comment by shomatan** [comment]
- #151
