### ISSUE TITLE
Webロゴ掲載（株式会社サムライズムさま）

### ISSUE THREAD

**Issue by shomatan** [scalamatsuri/2024.scalamatsuri.org#298]
## やること

- [ ] リポジトリにロゴを入れる
  - ロゴ画像:
- [ ] `data/sponsors.json` を変更する
- [ ] master branch に向けて PullRequest を送る
- [ ] staging 環境で表示を確認する
- [ ] master から production に向けて自動で PullRequest が作成されるのでマージ
- [ ] merge 後、production 環境の Web サイトに反映されていることを確認する
- [ ] speakerdeck のスライドが指定された場合、URL のみ切り取って `"speakerdeckUrl": ""` に指定する。
  - 2024 年 2 月: 現在 slideHtml が機能しておらず、iframe 内部が空で表示されてしまう模様。
  - 2024 年 2 月: speakerdeck 以外の URL を指定された場合は別途 WEB サイトチームにご相談ください。

```
  {
    "id": "SAMURAI_1",
    "type": "SAMURAI",
    "ja": {
      "name": "侍スポンサー1"
    },
    "en": {
      "name": "Samurai Sponsor1"
    },
    "logo": "/img/sponsors/scalamatsuri_logo.png",
    "url": "",
    "textHtml": "<p>侍スポンサー1です。</p>",
    "slideHtml": "",
    "speakerdeckUrl": ""
  },
```

**Comment by tomoco95** [comment]
#317 で完了しています！
